services:
  php:
    image: php:8.4-fpm-alpine3.20
    container_name: php
    volumes:
      - ./app:/var/www/html:ro
      - ./config/php/entrypoint.sh:/entrypoint.sh
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
    depends_on:
      - minio
    networks:
      - app-network
    entrypoint: /entrypoint.sh
    command: php-fpm
  nginx:
    image: nginx:mainline-alpine-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html:ro
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    networks:
      - app-network
  openobserve:
    image: openobserve/openobserve:latest
    container_name: openobserve
    environment:
      ZO_TELEMETRY: false
      ZO_ROOT_USER_EMAIL: ${OO_USER}
      ZO_ROOT_USER_PASSWORD: ${OO_PASSWORD}
    ports:
      - 5080:5080
    volumes:
      - openobserve-data:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  minio-data:
  openobserve-data:
